namespace wwfpp.Models.Payroll
{
    public class EmployeeSalaryFinalViewModel
    {
        public int final_salary_id { get; set; }  //[numeric{18, 0) NOT NULL,
        public int? emp_id { get; set; }//[int] NULL,
        public short? sal_year { get; set; }  //[smallint] NULL,
        public short? sal_month { get; set; }  //[smallint] NULL,
        public string? fiscal_year { get; set; }  //[nvarchar](10) NULL,
        public byte? emp_week { get; set; }  //[tinyint] NULL,
        public DateTime? sal_start_date { get; set; }  //[datetime] NULL,
        public DateTime? sal_end_date { get; set; }  //[datetime] NULL,
        public DateTime? submit_date { get; set; }  //[datetime] NULL,
        public int? submit_by { get; set; }  //[int] NULL,
        public decimal? act_basic_salary { get; set; }  //[money] NULL,
        public decimal? act_pf_a { get; set; }  //[money] NULL,
        public decimal? act_remote_area_all { get; set; }  //[money] NULL,
        public decimal? less_remote_exemption { get; set; }  //[money] NULL,
        public decimal? welfare_fund_contribution { get; set; }  //[money] NULL,
        public decimal? welfare_fund_interest { get; set; }  //[money] NULL,
        public decimal? welfare_fund_paid { get; set; }  //[money] NULL,
        public decimal? welfare_fund_payable { get; set; }  //[money] NULL,
        public decimal? less_adv_personal { get; set; }  //[money] NULL,
        public decimal? less_adv_program { get; set; }  //[money] NULL,
        public decimal? less_adv_travel { get; set; }  //[money] NULL,
        public decimal? less_adv_field { get; set; }  //[money] NULL,
        public decimal? less_loan_welfare { get; set; }  //[money] NULL,
        public decimal? less_loan_pf { get; set; }  //[money] NULL,
        public decimal? less_loan_cit { get; set; }  //[money] NULL,
        public string? leave_accrual_payble_included { get; set; }  //[varchar{1) NULL,
        public string? leave_accrual_payble_tax_percent { get; set; }  //[float] NULL,
        public decimal? leave_accrual_payble_tax_amount { get; set; }  //[money] NULL,
        public decimal? leave_accrual_payble_amount { get; set; }  //[money] NULL,
        public string? gratuity_accrual_payble_included { get; set; }  //[varchar{1) NULL,
        public double? gratuity_accrual_payble_tax_percent { get; set; }  //[float] NULL,
        public decimal? gratuity_accrual_payble_tax_amount { get; set; }  //[money] NULL,
        public decimal? gratuity_accrual_payble_amount { get; set; }  //[money] NULL,
        public string? percent_for_tax_add { get; set; }  //[nvarchar](1) NULL,
        public decimal? salary_paid { get; set; }  //[money] NULL,
        public decimal? salary_payable { get; set; }  //[money] NULL,
        public decimal? pf_a_paid { get; set; }  //[money] NULL,
        public decimal? pf_a_payable { get; set; }  //[money] NULL,
        public decimal? children_edu_all_paid { get; set; }  //[money] NULL,
        public decimal? children_edu_all_payable { get; set; }  //[money] NULL,
        public decimal? overtime_paid { get; set; }  //[money] NULL,
        public decimal? overtime_payable { get; set; }  //[money] NULL,
        public decimal? performance_all_paid { get; set; }  //[money] NULL,
        public decimal? performance_all_payable { get; set; }  //[money] NULL,
        public decimal? insurance_paid { get; set; }  //[money] NULL,
        public decimal? insurance_payable { get; set; }  //[money] NULL,
        public decimal? remote_area_all_paid { get; set; }  //[money] NULL,
        public decimal? remote_area_all_payable { get; set; }  //[money] NULL,
        public decimal? others_paid { get; set; }  //[money] NULL,
        public decimal? others_payable { get; set; }  //[money] NULL,
        public string? others_remarks { get; set; }  //[nvarchar](250) NULL,
        public decimal? dashain_a_paid { get; set; }  //[money] NULL,
        public decimal? dashain_a_payable { get; set; }  //[money] NULL,
        public string? is_dashain { get; set; }  //[nvarchar](1) NULL,
        public decimal? pf_d_deducted { get; set; }  //[money] NULL,
        public decimal? pf_d_deductable { get; set; }  //[money] NULL,
        public decimal? cit_d_deducted { get; set; }  //[money] NULL,
        public decimal? cit_d_deductable { get; set; }  //[money] NULL,
        public decimal? betalibi_d_deducted { get; set; }  //[money] NULL,
        public decimal? betalibi_d_deductable { get; set; }  //[money] NULL,
        public decimal? taxable_salary { get; set; }  //[money] NULL,
        public decimal? payable_salary { get; set; }  //[money] NULL,
        public decimal? gross_tax { get; set; }  //[money] NULL,
        public decimal? medical_d_on_tax_deducted { get; set; }  //[money] NULL,
        public decimal? medical_d_on_tax_deductable { get; set; }  //[money] NULL,
        public decimal? pre_access_tax { get; set; }  //[money] NULL,
        public decimal? less_tax_deducted { get; set; }  //[money] NULL,
        public decimal? less_tax_deductable { get; set; }  //[money] NULL,
        public decimal? net_payble_salary { get; set; }  //[money] NULL,
        public decimal? net_in_hand { get; set; }  //[money] NULL,
        public string? remarks { get; set; }  //[nvarchar](250) NULL,
        public decimal? marital_basic_d { get; set; }  //[money] NULL,
        public decimal? less_insurance_d { get; set; }  //[money] NULL,
        public short? counter { get; set; }  //[smallint] NULL,
        public decimal? leave_encashment_paid { get; set; }  //[money] NULL,
        public decimal? leave_encashment_payble { get; set; }  //[money] NULL,
        public decimal? gratuity_paid { get; set; }  //[money] NULL,
        public decimal? gratuity_payble { get; set; }  //[money] NULL,
        public decimal? medical_reim_paid { get; set; }  //[money] NULL,
        public decimal? medical_reim_payble { get; set; }  //[money] NULL,
        public decimal? medical_eli_paid { get; set; }  //[money] NULL,
        public decimal? medical_eli_payble { get; set; }  //[money] NULL,
    }

}
