namespace wwfpp.Models.Payroll
{
    public class EmployeeSalaryViewModel
    {
        public int salary_id { get; set; }  //[real] NOT NULL, [NOTE: change on database to int]
        public int? emp_id { get; set; }
        public short? sal_year { get; set; }  //[smallint] NULL,
        public short? sal_month { get; set; }  //[smallint] NULL,
        public decimal? basic_salary { get; set; }  //[money] NULL,
        public decimal? grade { get; set; }  //[money] NULL,
        public decimal? pf_a { get; set; }  //[money] NULL,
        public decimal? children_edu_all { get; set; }  //[money] NULL,
        public decimal? performance_all { get; set; }  //[money] NULL,
        public decimal? remote_area_all { get; set; }  //[money] NULL,
        public decimal? others { get; set; }  //[money] NULL,
        public decimal? overtime { get; set; }  //[money] NULL,
        public decimal? pf_d { get; set; }  //[money] NULL,
        public decimal? incometax_d { get; set; }  //[money] NULL,
        public decimal? insurance_d { get; set; }  //[money] NULL,
        public decimal? cit_d { get; set; }  //[money] NULL,
        public decimal? betalibi_d { get; set; }  //[money] NULL,
        public string? is_dashain { get; set; }  //[nvarchar](1) NULL,
        public decimal? dashain_a { get; set; }  //[money] NULL,
        public decimal? tel_per_adv { get; set; }  //[money] NULL,
        public decimal? travel_prog_adv { get; set; }  //[money] NULL,
        public string? remarks { get; set; }  //[nvarchar](100) NULL,
        public DateTime? submit_date { get; set; }  //[datetime] NULL,
        public int? submit_by { get; set; }  //[int] NULL,
        public string? percent_for_tax_add { get; set; }  //[nvarchar](1) NULL,
        public decimal? medical_deduction_on_tax { get; set; }  //[money] NULL,
        public decimal? welfare_fund { get; set; }  //[money] NULL,
        public decimal? remote_exem { get; set; }  //[money] NULL,
        public decimal? gratudi { get; set; }  //[money] NULL,
        public decimal? act_basic_salary { get; set; }  //[money] NULL,
        public decimal? act_pf_a { get; set; }  //[money] NULL,
        public decimal? act_remote_area_all { get; set; }  //[money] NULL,
        public decimal? act_pf_d { get; set; }  //[money] NULL,
        public decimal? a_cit_d { get; set; }  //[money] NULL,
        public string? cit_type { get; set; }  //[nvarchar](1) NULL,
        public double? cit_percent_amonnt { get; set; }  //[float] NULL,
        public decimal? marital_d { get; set; }  //[money] NULL,
        public decimal? yearly_salary { get; set; }  //[money] NULL,
        public decimal? yearly_tax { get; set; }  //[money] NULL,
        public decimal? monthly_salary { get; set; }  //[money] NULL,
        public decimal? month_amount { get; set; }  //[money] NULL,
        public decimal? pr_adv { get; set; }  //[money] NULL,
        public decimal? fd_adv { get; set; }  //[money] NULL,
        public decimal? wl_adv { get; set; }  //[money] NULL,
        public decimal? wl_per { get; set; }  //[money] NULL,
        public decimal? net_in_hand { get; set; }  //[money] NULL,
        public decimal? insurance { get; set; }  //[money] NULL,
        public decimal? first_taxable_amount { get; set; }  //[money] NULL,
        public double? initial_tax_percent { get; set; }  //[float] NULL,
        public double? first_tax_percent { get; set; }  //[float] NULL,
        public double? second_tax_percent { get; set; }  //[float] NULL,
        public decimal? pre_access_tax { get; set; }  //[money] NULL,
        public decimal? adv_PF_loan { get; set; }  //[money] NULL,
        public decimal? adv_CIT_loan { get; set; }  //[money] NULL,
        public decimal? d_3_amt { get; set; }  //[money] NULL,
        public double? d_3_p { get; set; }  //[float] NULL,
        public double? d_4_p { get; set; }  //[float] NULL,
        public string? fiscal_year { get; set; }  //[nvarchar](10) NULL,
        public byte? emp_week { get; set; }  //[tinyint] NULL,
        public decimal? gratuity { get; set; }  //[money] NULL,
        public decimal? gratuity_ded { get; set; }  //[money] NULL,
        public decimal? medical_expense_reimburse_eligible { get; set; }  //[money] NULL,
        public decimal? medical_expense_reimburse_total { get; set; }  //[money] NULL,
        public decimal? leave_encash { get; set; }  //[money] NULL,
        public decimal? second_tax_amount { get; set; }  //[money] NULL,
        public double? gender_ded_per { get; set; }  //[float] NULL,
        public decimal? ssf { get; set; }  //[money] NULL,
        public decimal? ssf_ded { get; set; }  //[money] NULL,
        public decimal? insurance_d_nl { get; set; }  //[money] NULL,
        public decimal? fourth_tax_amount { get; set; }  //[money] NULL,
        public double? fifth_tax_percent { get; set; }  //[float] NULL,
        public decimal? annual_health_checkup_add { get; set; }  //[money] NULL,
        public decimal? annual_health_checkup_ded { get; set; }  //[money] NULL,
    }

}
